version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: database
    volumes:
      - db_data:/var/lib/postgresql/data 
  app:
      build: .
      ports:
        - "8000:8000"
      depends_on:
        - db
      volumes:
        - .:/app

volumes:
  db_data:
